import type { Metadata } from "next";
import "./globals.css";
import { LanguageProvider } from "@/context/LanguageContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "PokeApp IES Cura Valera",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal // <--- ¡IMPORTANTE! Recibimos el slot del modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="d-flex flex-column min-vh-100">
        <LanguageProvider>
          <Header />
          <main className="container flex-grow-1">
            {children}
            {modal} {/* <--- ¡IMPORTANTE! Renderizamos el modal aquí */}
          </main>
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}